-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 09:51:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imgboard
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `imgboard` ;

-- -----------------------------------------------------
-- Schema imgboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imgboard` DEFAULT CHARACTER SET utf8 ;
USE `imgboard` ;

-- -----------------------------------------------------
-- Table `imgboard`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgboard`.`users` ;

CREATE TABLE IF NOT EXISTS `imgboard`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imgboard`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgboard`.`pictures` ;

CREATE TABLE IF NOT EXISTS `imgboard`.`pictures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imgboard`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgboard`.`favorites` ;

CREATE TABLE IF NOT EXISTS `imgboard`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `pictures_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `pictures_id`),
  INDEX `fk_favorites_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_favorites_pictures1_idx` (`pictures_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `imgboard`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_pictures1`
    FOREIGN KEY (`pictures_id`)
    REFERENCES `imgboard`.`pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imgboard`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgboard`.`tags` ;

CREATE TABLE IF NOT EXISTS `imgboard`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imgboard`.`tags_pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgboard`.`tags_pictures` ;

CREATE TABLE IF NOT EXISTS `imgboard`.`tags_pictures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pictures_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pictures_id`, `tags_id`),
  INDEX `fk_tags_pictures_pictures1_idx` (`pictures_id` ASC) VISIBLE,
  INDEX `fk_tags_pictures_tags1_idx` (`tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_tags_pictures_pictures1`
    FOREIGN KEY (`pictures_id`)
    REFERENCES `imgboard`.`pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_pictures_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `imgboard`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
